// Code generated by "stringer -type=AddressKind"; DO NOT EDIT.

package libada

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LegacyAddressKind-0]
	_ = x[BaseAddressKind-1]
	_ = x[PointerAddressKind-2]
	_ = x[EnterpriseAddressKind-3]
	_ = x[RewardAddressKind-4]
}

const _AddressKind_name = "LegacyAddressBaseAddressPointerAddressEnterpriseAddressRewardAddress"

var _AddressKind_index = [...]uint8{0, 13, 24, 38, 55, 68}

func (i AddressKind) String() string {
	if i >= AddressKind(len(_AddressKind_index)-1) {
		return "AddressKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddressKind_name[_AddressKind_index[i]:_AddressKind_index[i+1]]
}
