name: test
on:
  - push
  - pull_request

jobs:
  test_1_16:
    runs-on: ubuntu-latest
    name: tests with go1.16
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: run unit test
        run: go test -v -race .
